services:
  app:
    build: .
    container_name: laravel-sqlsrv
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    environment:
      DB_CONNECTION: sqlsrv
      DB_HOST: sqlsrv
      DB_PORT: 1433
      DB_DATABASE: your_database
      DB_USERNAME: sa
      DB_PASSWORD: YourStrong!Passw0rd
    depends_on:
      - sqlsrv

  sqlsrv:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql2017
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
    driver: local